/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-01-27 16:05:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gallery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1485456599038L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1485461311733L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>V.T.A.C</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom Fonts -->\n");
      out.write("    <link href=\"css/fonts/awesomeFont.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    \n");
      out.write("    <link href='css/slick-theme.css' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='css/slick-theme.less' rel='stylesheet' type='text/less'>\n");
      out.write("    <link href='css/slick-theme.scss' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='css/slick.scss' rel='stylesheet' type='text/css'>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <style></style>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- Theme CSS -->\n");
      out.write("    <link href=\"css/agency.min.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <link href=\"css/gallery.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("    \n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\t<style></style>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"page-top\" class=\"index\">\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    \n");
      out.write("    ");
      out.write("<nav id=\"mainNav\" class=\"navbar navbar-default navbar-custom navbar-fixed-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("            <div class=\"navbar-header page-scroll\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span> Menu <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a href=\"index.jsp\">\r\n");
      out.write("                \t<img src=\"img/Logo_VTAC1.png\" id=\"vtacLogo\"/>\r\n");
      out.write("                </a>\r\n");
      out.write("<!--                 <a class=\"navbar-brand page-scroll\" href=\"#page-top\">Start Bootstrap</a> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"navbar-header page-scroll fulltime\">\r\n");
      out.write("\t            <h3>24 Hours Plumbing Service</h3>\r\n");
      out.write("\t            <h4>");
      out.print(com.vtac.parameters.Parameters.telephone );
      out.write("</h4>\r\n");
      out.write("    </div>\r\n");
      out.write("            \t\r\n");
      out.write("            \r\n");
      out.write("            \t\r\n");
      out.write("\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                    <li class=\"hidden\">\r\n");
      out.write("                        <a href=\"#page-top\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("<!--                     <li> -->\r\n");
      out.write("<!--                         <a class=\"page-scroll\" href=\"index.jsp#ourCompany\">Our Company</a> -->\r\n");
      out.write("<!--                     </li> -->\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"about.jsp\">Projects</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"portfolio.jsp\">Portfolio</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"gallery.jsp\">Gallery</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <!--  <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"#team\">Team</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container-fluid -->\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Header -->\n");
      out.write("    \n");
      out.write(" \n");
      out.write("    <section id=\"contact\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    <h2 class=\"section-heading\">Gallery</h2>\n");
      out.write("\t\t\t\t<h3 class=\"section-subheading text-muted\">Following are sample\n");
      out.write("\t\t\t\t\tgalleries of our work</h3>\n");
      out.write("\t\t\t</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"slick-carousel\">\n");
      out.write("\t\t\t\t\t<!-- <div><img src=\"img/gallery/1.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/2.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/3.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/4.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/1.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/2.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/3.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/4.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/1.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/2.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/3.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/4.JPG\"></div>\n");
      out.write("\t\t\t\t\t-->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("\t\t\t<div class=\"slick-carousel-nav\">\n");
      out.write("\t\t\t\t\t<!--<div><img src=\"img/gallery/1.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/2.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/3.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/4.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/1.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/2.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/3.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/4.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/1.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/2.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/3.JPG\"></div>\n");
      out.write("\t\t\t\t\t<div><img src=\"img/gallery/4.JPG\"></div>\n");
      out.write("\t\t\t\t\t-->\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    \n");
      out.write("        ");
      out.write("<footer>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <span class=\"copyright\">Copyright &copy; VTAC inc. 2017</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <ul class=\"list-inline social-buttons\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"https://www.facebook.com/VTAC-Plumbing-HVAC-Utility-Contractor-122173147797883\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <ul class=\"list-inline quicklinks\">\r\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">Terms of Use</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </footer>");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"//cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <script src=\"js/gallery.js\"></script>\n");
      out.write("    \n");
      out.write("    <script src=\"js/slick.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Plugin JavaScript -->\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Contact Form JavaScript -->\n");
      out.write("    <script src=\"js/jqBootstrapValidation.js\"></script>\n");
      out.write("    <script src=\"js/contact_me.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Theme JavaScript -->\n");
      out.write("    <script src=\"js/agency.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
